# Generated by Django 4.2.7 on 2023-12-02 19:29

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trader',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('image', models.ImageField(upload_to='img/trader', verbose_name='Фотография')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('country', models.CharField(blank=True, max_length=255, null=True, verbose_name='Страна')),
                ('city', models.CharField(blank=True, max_length=255, null=True, verbose_name='Город')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес')),
                ('email_verified', models.BooleanField(default=False, verbose_name='Проверка почты')),
                ('theme', models.CharField(choices=[('light', 'light'), ('dark', 'dark')], default='light', max_length=255, verbose_name='Тема')),
                ('status', models.CharField(choices=[('active', 'active'), ('locked', 'locked')], default='active', max_length=255, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Трейдер',
                'verbose_name_plural': 'Трейдеры',
                'ordering': ['id'],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Credit_card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('number', models.CharField(max_length=16, verbose_name='Номер')),
                ('expiration_date', models.DateField(verbose_name='Дата окончания срока')),
                ('cvv', models.CharField(max_length=4, verbose_name='CVV')),
                ('card_type', models.CharField(choices=[('VISA', 'Visa'), ('MASTERCARD', 'MasterCard'), ('AMEX', 'American Express')], max_length=255, verbose_name='Тип карты')),
                ('trader', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='trading.trader', verbose_name='Трейдер')),
            ],
            options={
                'verbose_name': 'Кредитная карта',
                'verbose_name_plural': 'Кредитные карты',
                'ordering': ['id'],
            },
        ),
    ]
