# Generated by Django 4.2.7 on 2023-12-04 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
        ('trading', '0002_alter_trader_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trader',
            name='country',
        ),
        migrations.AlterField(
            model_name='trader',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='location.city'),
        ),
    ]
