# Generated by Django 4.2.7 on 2023-12-06 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0003_remove_trader_country_alter_trader_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='trader',
            name='bot_first_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='trader',
            name='bot_lang_code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Язык'),
        ),
        migrations.AddField(
            model_name='trader',
            name='bot_last_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Фамилия'),
        ),
        migrations.AddField(
            model_name='trader',
            name='bot_phone_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Телефонный номер'),
        ),
        migrations.AddField(
            model_name='trader',
            name='bot_user_id',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='ID пользователя'),
        ),
        migrations.AddField(
            model_name='trader',
            name='bot_username',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя пользователя'),
        ),
    ]
