# Generated by Django 4.2.7 on 2023-12-08 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0004_trader_bot_first_name_trader_bot_lang_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credit_card',
            name='number',
            field=models.CharField(max_length=255, verbose_name='Номер'),
        ),
    ]
