# Generated by Django 4.2.7 on 2023-12-08 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0005_alter_credit_card_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='trader',
            name='choose_currency',
            field=models.BooleanField(default=False, verbose_name='Выбрал валюту'),
        ),
    ]
