# Generated by Django 4.2.7 on 2023-12-16 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0006_trader_choose_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='credit_card',
            name='verified',
            field=models.BooleanField(default=False, verbose_name='Verified'),
        ),
    ]
