# Generated by Django 4.2.7 on 2023-12-16 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0007_credit_card_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credit_card',
            name='card_type',
            field=models.CharField(blank=True, choices=[('VISA', 'Visa'), ('MASTERCARD', 'MasterCard'), ('AMEX', 'American Express')], max_length=255, null=True, verbose_name='Тип карты'),
        ),
    ]
