# Generated by Django 4.2.7 on 2023-12-19 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0008_alter_credit_card_card_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('symbol', models.CharField(max_length=10)),
                ('currency_type', models.CharField(choices=[('fiat', 'Fiat'), ('crypto', 'Crypto')], max_length=10)),
                ('country', models.CharField(blank=True, max_length=50, null=True)),
                ('blockchain', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Валюта',
                'verbose_name_plural': 'Валюты',
                'ordering': ['id'],
            },
        ),
    ]
