# Generated by Django 4.2.7 on 2023-12-20 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0010_alter_trader_city_exchange'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='blockchain',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Блокчейн'),
        ),
        migrations.AlterField(
            model_name='currency',
            name='country',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='currency',
            name='currency_type',
            field=models.CharField(choices=[('fiat', 'Fiat'), ('crypto', 'Crypto')], max_length=10, verbose_name='Тип валюты'),
        ),
        migrations.AlterField(
            model_name='currency',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='currency',
            name='symbol',
            field=models.CharField(max_length=10, verbose_name='Символ'),
        ),
    ]
