# Generated by Django 4.2.7 on 2023-12-24 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0011_alter_currency_blockchain_alter_currency_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchange',
            name='confirmed',
            field=models.BooleanField(default=False, verbose_name='Подтверждено'),
        ),
    ]
