# Generated by Django 4.2.7 on 2023-12-24 00:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0012_exchange_confirmed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchange',
            name='trader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trading.trader', verbose_name='Трейдер'),
        ),
    ]
