# Generated by Django 4.2.7 on 2023-12-26 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0013_alter_exchange_trader'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchange',
            name='exchange_type',
            field=models.CharField(blank=True, choices=[('buy', 'buy'), ('sell', 'sell')], max_length=255, null=True, verbose_name='Тип обмена'),
        ),
    ]
