# Generated by Django 4.2.7 on 2023-12-31 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0015_currency_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currency',
            name='status',
        ),
    ]
