# Generated by Django 4.2.7 on 2023-12-31 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0016_remove_currency_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Статус'),
        ),
    ]
