# Generated by Django 4.2.7 on 2023-12-31 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0017_currency_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchange',
            name='amount_input',
            field=models.FloatField(default=0, verbose_name='Количество ввода'),
        ),
        migrations.AlterField(
            model_name='exchange',
            name='amount_output',
            field=models.FloatField(default=0, verbose_name='Количество выхода'),
        ),
    ]
