# Generated by Django 4.2.7 on 2023-12-31 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0018_alter_exchange_amount_input_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchange',
            name='exchange_type',
            field=models.CharField(choices=[('buy', 'buy'), ('sell', 'sell')], default='buy', max_length=255, verbose_name='Тип обмена'),
        ),
    ]
