# Generated by Django 4.2.7 on 2024-01-08 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0020_trader_bot_registration_finished'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchange',
            name='currency_type',
            field=models.CharField(choices=[('fiat', 'fiat'), ('crypto', 'crypto')], default='fiat', max_length=255, verbose_name='Тип валюты'),
        ),
    ]
