# Generated by Django 4.2.7 on 2024-01-08 23:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0021_exchange_currency_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchange',
            name='currency_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='currency_from', to='trading.currency', verbose_name='Валюта (из)'),
        ),
        migrations.AlterField(
            model_name='exchange',
            name='currency_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='currency_to', to='trading.currency', verbose_name='Валюта (в)'),
        ),
    ]
