# Generated by Django 4.2.7 on 2024-01-09 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0022_alter_exchange_currency_from_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Balance_update',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_type', models.CharField(choices=[('plus', 'plus'), ('minus', 'minus')], max_length=255, verbose_name='Тип обновления')),
                ('amount', models.FloatField(default=0, verbose_name='Количество')),
                ('payed', models.BooleanField(default=False, verbose_name='Оплачено')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='trading.currency', verbose_name='Валюта')),
                ('trader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trading.trader', verbose_name='Трейдер')),
            ],
            options={
                'verbose_name': 'Balance_update',
                'verbose_name_plural': 'Balance_updates',
                'ordering': ['id'],
            },
        ),
    ]
