# Generated by Django 4.2.7 on 2024-01-12 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0023_balance_update'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='balance_update',
            options={'ordering': ['id'], 'verbose_name': 'Обновление баланса', 'verbose_name_plural': 'Обновления балансов'},
        ),
    ]
