# Generated by Django 4.2.7 on 2024-01-16 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0024_alter_balance_update_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchange',
            name='credit_card',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Кредитная карта'),
        ),
    ]
