# Generated by Django 4.2.7 on 2024-01-18 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0025_exchange_credit_card'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock_amount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='Сумма')),
            ],
            options={
                'verbose_name': 'Стоковая сумма',
                'verbose_name_plural': 'Стоковые суммы',
                'ordering': ['amount'],
            },
        ),
        migrations.AddField(
            model_name='currency',
            name='stock_amount',
            field=models.ManyToManyField(blank=True, to='trading.stock_amount', verbose_name='Стоковые суммы'),
        ),
    ]
