# Generated by Django 4.2.7 on 2024-01-18 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0027_rename_stock_amount_currency_stock_amounts'),
    ]

    operations = [
        migrations.AddField(
            model_name='balance_update',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('plus', 'plus'), ('minus', 'minus')], max_length=255, null=True, verbose_name='Тип оплаты'),
        ),
    ]
