# Generated by Django 4.2.7 on 2024-01-20 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0029_alter_balance_update_payment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchange',
            name='wallet',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Кошелёк'),
        ),
    ]
