# Generated by Django 4.2.7 on 2024-01-21 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0031_alter_balance_update_payment_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Withdraw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_type', models.CharField(choices=[('fiat', 'fiat'), ('crypto', 'crypto')], default='fiat', max_length=255, verbose_name='Тип валюты')),
                ('amount', models.FloatField(default=0, verbose_name='Количество')),
                ('credit_card', models.CharField(blank=True, max_length=255, null=True, verbose_name='Кредитная карта')),
                ('wallet', models.CharField(blank=True, max_length=255, null=True, verbose_name='Кошелёк')),
                ('confirmed', models.BooleanField(default=False, verbose_name='Подтверждено')),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='trading.currency', verbose_name='Валюта')),
                ('trader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trading.trader', verbose_name='Трейдер')),
            ],
            options={
                'verbose_name': 'Вывод средств',
                'verbose_name_plural': 'Выводы средств',
                'ordering': ['id'],
            },
        ),
    ]
