# Generated by Django 4.2.7 on 2024-01-21 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0032_withdraw'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdraw',
            name='accepted',
            field=models.BooleanField(default=False, verbose_name='Принято'),
        ),
    ]
