# Generated by Django 4.2.7 on 2024-01-23 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0033_withdraw_accepted'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rate_template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=1, verbose_name='Цена')),
                ('currency_from', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='currency_from+', to='trading.currency', verbose_name='Валюта из')),
                ('currency_to', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='currency_to+', to='trading.currency', verbose_name='Валюта в')),
            ],
            options={
                'verbose_name': 'Шаблон валюты',
                'verbose_name_plural': 'Шаблоны валют',
                'ordering': ['currency_from'],
            },
        ),
    ]
