# Generated by Django 4.2.7 on 2024-01-23 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0034_rate_template'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rate_template',
            options={'ordering': ['currency_from', 'currency_to', 'amount'], 'verbose_name': 'Шаблон валюты', 'verbose_name_plural': 'Шаблоны валют'},
        ),
    ]
