# Generated by Django 4.2.7 on 2024-01-27 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0036_exchange_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='balance_update',
            name='currency_type',
            field=models.CharField(choices=[('fiat', 'fiat'), ('crypto', 'crypto')], default='fiat', max_length=255, verbose_name='Тип валюты'),
        ),
    ]
