# Generated by Django 4.2.7 on 2024-01-27 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0037_balance_update_currency_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='trader',
            name='hash_code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Хеш'),
        ),
    ]
