# Generated by Django 4.2.7 on 2024-01-27 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0038_trader_hash_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='balance_update',
            name='wallet',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Кошелёк'),
        ),
    ]
