# Generated by Django 4.2.7 on 2024-01-27 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0039_balance_update_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='wallet',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Кошелёк'),
        ),
    ]
