# Generated by Django 4.2.7 on 2024-01-27 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0040_currency_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='balance_update',
            name='confirmed',
            field=models.BooleanField(default=False, verbose_name='Подтверждено'),
        ),
    ]
