# Generated by Django 4.2.7 on 2024-01-28 00:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0041_balance_update_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdraw',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата'),
        ),
        migrations.CreateModel(
            name='Send',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_type', models.CharField(choices=[('fiat', 'fiat'), ('crypto', 'crypto')], default='fiat', max_length=255, verbose_name='Тип валюты')),
                ('amount', models.FloatField(default=0, verbose_name='Количество')),
                ('confirmed', models.BooleanField(default=False, verbose_name='Подтверждено')),
                ('accepted', models.BooleanField(default=False, verbose_name='Принято')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='trading.currency', verbose_name='Валюта')),
                ('receiver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='trading.trader', verbose_name='Получатель')),
                ('trader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trader', to='trading.trader', verbose_name='Трейдер')),
            ],
            options={
                'verbose_name': 'Отправка',
                'verbose_name_plural': 'Отправки',
                'ordering': ['id'],
            },
        ),
    ]
