# Generated by Django 4.2.7 on 2024-01-29 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0042_withdraw_date_send'),
    ]

    operations = [
        migrations.AddField(
            model_name='trader',
            name='subscription_type',
            field=models.CharField(choices=[('simple', 'Oval Simple'), ('medium', 'Oval Medium'), ('pro', 'Oval Pro')], default='simple', max_length=255, verbose_name='Тип пользователья'),
        ),
    ]
