# Generated by Django 4.2.7 on 2024-01-31 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0044_alter_balance_update_payment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='medium',
            field=models.BooleanField(default=False, verbose_name='Medium'),
        ),
        migrations.AddField(
            model_name='currency',
            name='pro',
            field=models.BooleanField(default=False, verbose_name='Pro'),
        ),
        migrations.AddField(
            model_name='currency',
            name='simple',
            field=models.BooleanField(default=False, verbose_name='Simple'),
        ),
    ]
