# Generated by Django 4.2.7 on 2024-01-31 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0045_currency_medium_currency_pro_currency_simple'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currency',
            name='pro',
        ),
    ]
