# Generated by Django 4.2.7 on 2024-02-01 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0047_currency_pro'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='medium_max_price',
            field=models.BooleanField(default=False, verbose_name='Medium max price'),
        ),
        migrations.AddField(
            model_name='currency',
            name='pro_max_price',
            field=models.BooleanField(default=True, verbose_name='Pro max price'),
        ),
        migrations.AddField(
            model_name='currency',
            name='simple_max_price',
            field=models.BooleanField(default=False, verbose_name='Simple max price'),
        ),
    ]
