# Generated by Django 4.2.7 on 2024-02-01 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0048_currency_medium_max_price_currency_pro_max_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currency',
            name='medium_max_price',
        ),
        migrations.RemoveField(
            model_name='currency',
            name='pro_max_price',
        ),
        migrations.RemoveField(
            model_name='currency',
            name='simple_max_price',
        ),
    ]
