# Generated by Django 4.2.7 on 2024-02-04 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0050_currency_medium_max_price_currency_pro_max_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchange',
            name='fees',
            field=models.FloatField(default=0, verbose_name='Комиссия'),
        ),
        migrations.AddField(
            model_name='withdraw',
            name='fees',
            field=models.FloatField(default=0, verbose_name='Комиссия'),
        ),
    ]
