# Generated by Django 4.2.7 on 2024-02-04 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0051_exchange_fees_withdraw_fees'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exchange',
            name='fees',
        ),
        migrations.RemoveField(
            model_name='withdraw',
            name='fees',
        ),
    ]
