# Generated by Django 4.2.7 on 2024-02-04 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0052_remove_exchange_fees_remove_withdraw_fees'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchange',
            name='fees',
            field=models.FloatField(default=1, verbose_name='Комиссия'),
        ),
        migrations.AddField(
            model_name='withdraw',
            name='fees',
            field=models.FloatField(default=1, verbose_name='Комиссия'),
        ),
    ]
