# Generated by Django 4.2.7 on 2024-02-12 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0053_exchange_fees_withdraw_fees'),
    ]

    operations = [
        migrations.AddField(
            model_name='trader',
            name='reff_hash_code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Хеш'),
        ),
    ]
