# Generated by Django 4.2.7 on 2024-02-13 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0054_trader_reff_hash_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='currency_type',
            field=models.CharField(choices=[('fiat', 'Fiat'), ('crypto', 'Crypto'), ('bonus', 'Bonus')], max_length=10, verbose_name='Тип валюты'),
        ),
    ]
