# Generated by Django 4.2.7 on 2024-02-18 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0058_send_denied'),
    ]

    operations = [
        migrations.AddField(
            model_name='send',
            name='message_id',
            field=models.BigIntegerField(default=0, verbose_name='ID сообщения'),
        ),
    ]
