# Generated by Django 4.2.7 on 2024-03-02 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0059_send_message_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='balance_update',
            name='bill',
            field=models.ImageField(null=True, upload_to='img/balance-bill', verbose_name='Чек'),
        ),
        migrations.AddField(
            model_name='balance_update',
            name='holder',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Держатель'),
        ),
        migrations.AlterField(
            model_name='trader',
            name='bot_lang_code',
            field=models.CharField(blank=True, default='ru', max_length=255, null=True, verbose_name='Язык'),
        ),
    ]
