# Generated by Django 4.2.7 on 2024-03-02 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0060_balance_update_bill_balance_update_holder_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='balance_update',
            name='holder',
        ),
        migrations.AddField(
            model_name='currency',
            name='holder',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Держатель'),
        ),
    ]
