# Generated by Django 4.2.7 on 2024-03-02 14:36

import apps.trading.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0061_remove_balance_update_holder_currency_holder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balance_update',
            name='bill',
            field=models.ImageField(null=True, upload_to=apps.trading.models.Balance_update.get_bill_path, verbose_name='Чек'),
        ),
    ]
