# Generated by Django 4.2.7 on 2023-12-08 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='bot_url',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка бота'),
        ),
    ]
