# Generated by Django 4.2.7 on 2024-01-07 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_about_bot_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tex_work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0, verbose_name='Очередь')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('name_en', models.CharField(max_length=255, null=True, verbose_name='Название')),
                ('name_ru', models.CharField(max_length=255, null=True, verbose_name='Название')),
                ('name_uz', models.CharField(max_length=255, null=True, verbose_name='Название')),
                ('name_de', models.CharField(max_length=255, null=True, verbose_name='Название')),
                ('name_hi', models.CharField(max_length=255, null=True, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('description_en', models.TextField(null=True, verbose_name='Описание')),
                ('description_ru', models.TextField(null=True, verbose_name='Описание')),
                ('description_uz', models.TextField(null=True, verbose_name='Описание')),
                ('description_de', models.TextField(null=True, verbose_name='Описание')),
                ('description_hi', models.TextField(null=True, verbose_name='Описание')),
                ('status', models.CharField(choices=[('active', 'active'), ('deactive', 'deactive')], default='active', max_length=255, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Tex_work',
                'verbose_name_plural': 'Tex_works',
                'ordering': ['order'],
            },
        ),
    ]
