# Generated by Django 4.2.7 on 2024-01-07 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_tex_work'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tex_work',
            options={'ordering': ['order'], 'verbose_name': 'Тех работа', 'verbose_name_plural': 'Тех работы'},
        ),
    ]
