# Generated by Django 4.2.7 on 2024-01-21 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_alter_tex_work_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='tex_work',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='img/tex_work', verbose_name='Постер'),
        ),
    ]
