# Generated by Django 4.2.7 on 2024-01-27 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0005_tex_work_poster'),
    ]

    operations = [
        migrations.CreateModel(
            name='Explanation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('explanation_type', models.CharField(choices=[('hash', 'Мой хеш')], max_length=255, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('description_en', models.TextField(null=True, verbose_name='Описание')),
                ('description_ru', models.TextField(null=True, verbose_name='Описание')),
                ('description_uz', models.TextField(null=True, verbose_name='Описание')),
                ('description_de', models.TextField(null=True, verbose_name='Описание')),
                ('description_hi', models.TextField(null=True, verbose_name='Описание')),
                ('status', models.CharField(choices=[('active', 'active'), ('deactive', 'deactive')], default='active', max_length=255, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Explanation',
                'verbose_name_plural': 'Explanations',
                'ordering': ['id'],
            },
        ),
    ]
