# Generated by Django 4.2.7 on 2024-01-27 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0006_explanation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='explanation',
            options={'ordering': ['id'], 'verbose_name': 'Объяснение', 'verbose_name_plural': 'Объяснения'},
        ),
    ]
