# Generated by Django 4.2.7 on 2024-02-06 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0007_alter_explanation_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='explanation',
            name='explanation_type',
            field=models.CharField(choices=[('hash', 'Мой хеш'), ('reff_link', 'Oval partners')], max_length=255, verbose_name='Название'),
        ),
    ]
