"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 4.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-na^1w$mfibdn0ztab3=8$oo2z__wihfo$co$$6+frbi0auahcu'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
# DEBUG = False

# ALLOWED_HOSTS = []
ALLOWED_HOSTS = ['45.80.148.146', 'oval.lc', 'www.oval.lc']

CSRF_TRUSTED_ORIGINS = ['http://45.80.148.146', 'https://oval.lc', 'https://www.oval.lc']

# Application definition

INSTALLED_APPS = [
    'modeltranslation',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework', 'rosetta',
    'import_export',
]

LOCAL_APPS = [
    'apps.about',
    'apps.authentication',
    'apps.extra',
    'apps.location',
    'apps.main',
    'apps.notification',
    'apps.stories',
    'apps.subscription',
    'apps.trading',
]

INSTALLED_APPS += LOCAL_APPS

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [str(BASE_DIR / 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'apps.main.context_processors.load_company_data',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'oval',
        'USER': 'oval_user',
        'PASSWORD': 'oval-2023',
        'HOST': 'localhost',
        'PORT': '',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

LOGIN_URL = 'sign_in'


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en'

gettext = lambda s: s
LANGUAGES = (
    ('en', gettext('English')),
    ('ru', gettext('Russian')),
    ('uz', gettext('Uzbek')),
    ('de', gettext('German')),
    ('hi', gettext('Hindi')),
)
MODELTRANSLATION_LANGUAGES = ('en', 'ru', 'uz', 'de', 'hi')

MODELTRANSLATION_TRANSLATION_FILES = (
    'apps.about.translation',
    'apps.extra.translation',
    'apps.location.translation',
    'apps.main.translation',
    'apps.trading.translation',
)

TIME_ZONE = "Asia/Tashkent"

USE_I18N = True

USE_TZ = False

LOCALE_PATHS = [
    BASE_DIR / "locale"
]


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_DIRS = [
    BASE_DIR / 'static'
]

# STATIC_ROOT = BASE_DIR / 'static'

MEDIA_URL = 'media/'

MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

EXCHANGERATE_TOKEN = '913e5ac9b5ea2fec06d2123a'

BOT_TOKEN = "6589754747:AAE8qamcP3GJo-ppi5F5Ct4GcGruvmh8SeM" # Lc
# BOT_TOKEN = "6931094772:AAFb4FkDU0PGXALS-O9V0MKYUadQeKm52qg" # Uz

SEND_GROUP_ID = {
    'fiat': '-4136911587',
    'crypto': '-4105790953',
}
WITHDRAW_GROUP_ID = {
    'fiat': '-4147417798',
    'crypto': '-4167681023',
}
BALANCE_GROUP_ID = {
    'fiat': '-4136512241',
    'crypto': '-4168654531',
}
EXCHANGE_GROUP_ID = {
    'fiat': '-1991572358',
    'crypto': '-1997971619',
}
