# Generated by Django 4.2.7 on 2024-02-10 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_alter_notification_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='_type',
            field=models.CharField(choices=[('exchange', 'Exchange'), ('withdraw', 'Withdraw'), ('send_sender', 'Send sender'), ('send_receiver', 'Send receiver'), ('subscription', 'Subscription'), ('balance_update', 'Balance update')], max_length=255, verbose_name='Тип уведомления'),
        ),
    ]
