# Generated by Django 4.2.7 on 2023-12-19 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='use_in_bot',
            field=models.BooleanField(default=False, verbose_name='Использовать в боте'),
        ),
    ]
