# Generated by Django 4.2.7 on 2024-01-26 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trading', '0036_exchange_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription_period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0, verbose_name='Очередь')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('name_en', models.CharField(max_length=255, null=True, verbose_name='Название')),
                ('name_ru', models.CharField(max_length=255, null=True, verbose_name='Название')),
                ('name_uz', models.CharField(max_length=255, null=True, verbose_name='Название')),
                ('name_de', models.CharField(max_length=255, null=True, verbose_name='Название')),
                ('name_hi', models.CharField(max_length=255, null=True, verbose_name='Название')),
                ('months', models.IntegerField(default=1, verbose_name='Месяца')),
                ('status', models.CharField(choices=[('active', 'active'), ('deactive', 'deactive')], default='active', max_length=255, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Периуд подписки',
                'verbose_name_plural': 'Периуды подписок',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Subscription_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0, verbose_name='Очередь')),
                ('name', models.CharField(choices=[('medium', 'Medium'), ('vip', 'Vip')], max_length=255, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('description_en', models.TextField(null=True, verbose_name='Описание')),
                ('description_ru', models.TextField(null=True, verbose_name='Описание')),
                ('description_uz', models.TextField(null=True, verbose_name='Описание')),
                ('description_de', models.TextField(null=True, verbose_name='Описание')),
                ('description_hi', models.TextField(null=True, verbose_name='Описание')),
                ('status', models.CharField(choices=[('active', 'active'), ('deactive', 'deactive')], default='active', max_length=255, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Тип подписки',
                'verbose_name_plural': 'Типы подписок',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Subscription_update',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_type', models.CharField(choices=[('plus', 'plus'), ('minus', 'minus')], max_length=255, verbose_name='Тип обновления')),
                ('days', models.IntegerField(default=0, verbose_name='Дни')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('subscription_type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='subscription.subscription_type', verbose_name='Тип подписки')),
                ('trader', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='trading.trader', verbose_name='Трейдер')),
            ],
            options={
                'verbose_name': 'Обновление подписки',
                'verbose_name_plural': 'Обновления подписок',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Subscription_price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(default=0, verbose_name='Цена')),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='trading.currency', verbose_name='Валюта')),
                ('subscription_period', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='subscription.subscription_period', verbose_name='Периуд подписки')),
                ('subscription_type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='subscription.subscription_type', verbose_name='Тип подписки')),
            ],
            options={
                'verbose_name': 'Цена подписки',
                'verbose_name_plural': 'Цены подписок',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(default=0, verbose_name='Цена')),
                ('payed', models.BooleanField(default=False, verbose_name='Оплачено')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='trading.currency', verbose_name='Валюта')),
                ('subscription_period', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='subscription.subscription_period', verbose_name='Периуд подписки')),
                ('subscription_type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='subscription.subscription_type', verbose_name='Тип подписки')),
                ('trader', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='trading.trader', verbose_name='Трейдер')),
            ],
            options={
                'verbose_name': 'Подписка',
                'verbose_name_plural': 'Подписки',
                'ordering': ['id'],
            },
        ),
    ]
