# Generated by Django 4.2.7 on 2024-01-27 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0002_subscription_period_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription_type',
            name='name',
            field=models.CharField(choices=[('simple', 'Oval Simple'), ('medium', 'Oval Medium'), ('pro', 'Oval Pro')], max_length=255, verbose_name='Название'),
        ),
    ]
