# Generated by Django 4.2.7 on 2024-01-27 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0003_alter_subscription_type_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription_type',
            name='price',
            field=models.FloatField(default=0, verbose_name='Цена'),
        ),
    ]
