# Generated by Django 4.2.7 on 2024-01-27 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0004_subscription_type_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription_type',
            name='price',
        ),
        migrations.AddField(
            model_name='subscription_price',
            name='initial_price',
            field=models.FloatField(default=0, verbose_name='Изначальная цена'),
        ),
    ]
