# Generated by Django 4.2.7 on 2024-01-30 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0005_remove_subscription_type_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('Payme', 'Payme'), ('Click', 'Click')], max_length=255, null=True, verbose_name='Тип оплаты'),
        ),
    ]
