# Generated by Django 4.2.7 on 2024-01-30 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0006_subscription_payment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='subscription_period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='subscription.subscription_period', verbose_name='Периуд подписки'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='subscription_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='subscription.subscription_type', verbose_name='Тип подписки'),
        ),
    ]
