# Generated by Django 4.2.7 on 2024-02-06 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0007_alter_subscription_subscription_period_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription_type',
            name='name',
            field=models.CharField(choices=[('simple', 'Oval Simple'), ('medium', 'Oval Pro'), ('pro', 'Oval Empire')], max_length=255, verbose_name='Название'),
        ),
    ]
