# Generated by Django 4.2.7 on 2024-02-08 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0008_alter_subscription_type_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription_type',
            name='is_popular',
            field=models.BooleanField(default=False, verbose_name='Популярный'),
        ),
    ]
