# Generated by Django 4.2.7 on 2024-02-08 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0010_subscription_feature'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscription_feature',
            options={'ordering': ['subscription_type', 'order'], 'verbose_name': 'Преимущество подписки', 'verbose_name_plural': 'Преимущества подписок'},
        ),
    ]
