# Generated by Django 4.2.7 on 2024-02-08 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0012_subscription_feature_name_de_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscription_feature',
            options={'ordering': ['subscription_type', 'order'], 'verbose_name': 'Преимущество подписки (для сайта)', 'verbose_name_plural': 'Преимущества подписок (для сайта)'},
        ),
        migrations.AlterField(
            model_name='subscription_type',
            name='description',
            field=models.TextField(verbose_name='Преимущество подписки (для бота)'),
        ),
        migrations.AlterField(
            model_name='subscription_type',
            name='description_de',
            field=models.TextField(null=True, verbose_name='Преимущество подписки (для бота)'),
        ),
        migrations.AlterField(
            model_name='subscription_type',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Преимущество подписки (для бота)'),
        ),
        migrations.AlterField(
            model_name='subscription_type',
            name='description_hi',
            field=models.TextField(null=True, verbose_name='Преимущество подписки (для бота)'),
        ),
        migrations.AlterField(
            model_name='subscription_type',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Преимущество подписки (для бота)'),
        ),
        migrations.AlterField(
            model_name='subscription_type',
            name='description_uz',
            field=models.TextField(null=True, verbose_name='Преимущество подписки (для бота)'),
        ),
    ]
